/**
 * GENERATED by pointset/hcps_export_params.m -- do not edit by hand.
 *
 * The HC/PS model's LOCKED DEFAULT (native 11x11 -- locked default, 2026-07-26).
 * Any figure that restates the model should read these rather than retype them:
 * the schematic previously carried sigma 0.60 deg / 64 point-sets / tauE 30 ms for a
 * day after that operating point was withdrawn, because the numbers were hand-written.
 */

export const HCPS_DEFAULTS = {
  sigDeg: 0.2424,
  sigPx: 7.273,
  v1grid: 11,
  nPointSets: 121,
  sigFrac: 1.5,
  fieldDeg: 4,
  PPD: 30,
  apertureNote: 'square field, 4 x 4 deg (a disc aperture of r = 2 deg is the other stationary option)',
  tauE_ms: 150,
  tau_ms: 15,
  frame_ms: 10,
  nDir: 8,
  nHue: 8,
  kappa: 2,
  kappaHue: 2,
  CoopL: 0.4,
  biasAmp: 16,
  normSigRF: 3.03,
  normSigPx: 22,
  normSigSpac: 2.02,
  normKapDir: 0,
  normKapHue: 0,
  normW: 1,
  sigNR: 1,
  nV1: 2,
  featureNorm: true,
  localNorm: true,
  biasInPool: true,
  ffNorm: true,
  ffScale: 3,
  ffFloor: 1e-06,
  probeDegPerSec: 2.26,
  transCoh: 0.5,
  probeFrames: [20, 24],
  nFrames: 35,
  readout: 'right-only (the opponent RATIO has a near-zero denominator in sparse/fast cells)',
  label: 'native 11x11 -- locked default, 2026-07-26',
  verifiedAgainst: 'hcps_grid_poster_map.m literal block: right-only AI +0.3916 at rho 4.99, 2.24 deg/s',
} as const;

export type HcpsDefaults = typeof HCPS_DEFAULTS;
